enum CAR_SLOT_ID {
	CARSLOTID_INVALID = -1,
	CARSLOTID_BADGING_BUMPER_SET_FRONT = 0x0,
	CARSLOTID_BADGING_BUMPER_SET_REAR = 0x1,
	CARSLOTID_BADGING_FENDER_FRONT_LEFT = 0x2,
	CARSLOTID_BADGING_FENDER_FRONT_RIGHT = 0x3,
	CARSLOTID_BADGING_FENDER_REAR_LEFT = 0x4,
	CARSLOTID_BADGING_FENDER_REAR_RIGHT = 0x5,
	CARSLOTID_BADGING_TRUNK = 0x6,
	CARSLOTID_BASE = 0x7,
	CARSLOTID_BODY = 0x8,
	CARSLOTID_BODY_DOORLINE = 0x9,
	CARSLOTID_BRAKE_CALIPER_FRONT = 0xA,
	CARSLOTID_BRAKE_CALIPER_REAR = 0xB,
	CARSLOTID_BRAKE_ROTOR_FRONT = 0xC,
	CARSLOTID_BRAKE_ROTOR_REAR = 0xD,
	CARSLOTID_BRAKELIGHT_GLASS_LEFT = 0xE,
	CARSLOTID_BRAKELIGHT_GLASS_RIGHT = 0xF,
	CARSLOTID_BRAKELIGHT_LEFT = 0x10,
	CARSLOTID_BRAKELIGHT_RIGHT = 0x11,
	CARSLOTID_BUMPER_FRONT = 0x12,
	CARSLOTID_BUMPER_FRONT_EXTRA = 0x13,
	CARSLOTID_BUMPER_REAR = 0x14,
	CARSLOTID_BUMPER_REAR_EXTRA = 0x15,
	CARSLOTID_CHASSIS = 0x16,
	CARSLOTID_DAMAGE_BODY = 0x17,
	CARSLOTID_DAMAGE_BRAKELIGHT_LEFT = 0x18,
	CARSLOTID_DAMAGE_BRAKELIGHT_RIGHT = 0x19,
	CARSLOTID_DAMAGE_BUMPER_FRONT = 0x1A,
	CARSLOTID_DAMAGE_BUMPER_REAR = 0x1B,
	CARSLOTID_DAMAGE_DOOR_LEFT = 0x1C,
	CARSLOTID_DAMAGE_DOOR_REAR_LEFT = 0x1D,
	CARSLOTID_DAMAGE_DOOR_REAR_RIGHT = 0x1E,
	CARSLOTID_DAMAGE_DOOR_RIGHT = 0x1F,
	CARSLOTID_DAMAGE_FENDER_FRONT_LEFT = 0x20,
	CARSLOTID_DAMAGE_FENDER_FRONT_RIGHT = 0x21,
	CARSLOTID_DAMAGE_HEADLIGHT_LEFT = 0x22,
	CARSLOTID_DAMAGE_HEADLIGHT_RIGHT = 0x23,
	CARSLOTID_DAMAGE_HOOD = 0x24,
	CARSLOTID_DAMAGE_SIDEMIRROR_LEFT = 0x25,
	CARSLOTID_DAMAGE_SIDEMIRROR_RIGHT = 0x26,
	CARSLOTID_DAMAGE_TRUNK = 0x27,
	CARSLOTID_DAMAGE_TRUNK911 = 0x28,
	CARSLOTID_DAMAGE_WIDEBODY = 0x29,
	CARSLOTID_DAMAGE_WIDEBODY_BUMPER_FRONT = 0x2A,
	CARSLOTID_DAMAGE_WIDEBODY_BUMPER_REAR = 0x2B,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_LEFT = 0x2C,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_REAR_LEFT = 0x2D,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_REAR_RIGHT = 0x2E,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_RIGHT = 0x2F,
	CARSLOTID_DAMAGE_WIDEBODY_FENDER_FRONT_LEFT = 0x30,
	CARSLOTID_DAMAGE_WIDEBODY_FENDER_FRONT_RIGHT = 0x31,
	CARSLOTID_DAMAGE_WINDOW_FRONT = 0x32,
	CARSLOTID_DAMAGE_WINDOW_FRONT_LEFT = 0x33,
	CARSLOTID_DAMAGE_WINDOW_FRONT_RIGHT = 0x34,
	CARSLOTID_DAMAGE_WINDOW_REAR = 0x35,
	CARSLOTID_DAMAGE_WINDOW_REAR_LEFT = 0x36,
	CARSLOTID_DAMAGE_WINDOW_REAR_RIGHT = 0x37,
	CARSLOTID_DECAL_FRONT_WINDOW = 0x38,
	CARSLOTID_DECAL_REAR_WINDOW = 0x39,
	CARSLOTID_DOOR_LEFT = 0x3A,
	CARSLOTID_DOOR_REAR_LEFT = 0x3B,
	CARSLOTID_DOOR_REAR_RIGHT = 0x3C,
	CARSLOTID_DOOR_RIGHT = 0x3D,
	CARSLOTID_DOORHANDLE_FRONT_LEFT = 0x3E,
	CARSLOTID_DOORHANDLE_FRONT_RIGHT = 0x3F,
	CARSLOTID_DOORHANDLE_REAR_LEFT = 0x40,
	CARSLOTID_DOORHANDLE_REAR_RIGHT = 0x41,
	CARSLOTID_DRIVER = 0x42,
	CARSLOTID_ENGINE = 0x43,
	CARSLOTID_EXHAUST = 0x44,
	CARSLOTID_EXHAUST_TIPS_CENTER = 0x45,
	CARSLOTID_EXHAUST_TIPS_LEFT = 0x46,
	CARSLOTID_EXHAUST_TIPS_RIGHT = 0x47,
	CARSLOTID_FENDER_FRONT_LEFT = 0x48,
	CARSLOTID_FENDER_FRONT_RIGHT = 0x49,
	CARSLOTID_HEADLIGHT_GLASS_LEFT = 0x4A,
	CARSLOTID_HEADLIGHT_GLASS_RIGHT = 0x4B,
	CARSLOTID_HEADLIGHT_LEFT = 0x4C,
	CARSLOTID_HEADLIGHT_RIGHT = 0x4D,
	CARSLOTID_HOOD = 0x4E,
	CARSLOTID_LICENSE_PLATE = 0x4F,
	CARSLOTID_LIGHTBAR = 0x50,
	CARSLOTID_ROLL_CAGE = 0x51,
	CARSLOTID_ROOF = 0x52,
	CARSLOTID_ROOF_INSIDE = 0x53,
	CARSLOTID_ROOFSCOOP = 0x54,
	CARSLOTID_SEAT_LEFT = 0x55,
	CARSLOTID_SEAT_RIGHT = 0x56,
	CARSLOTID_SIDEMIRROR_LEFT = 0x57,
	CARSLOTID_SIDEMIRROR_RIGHT = 0x58,
	CARSLOTID_SKIRT_LEFT = 0x59,
	CARSLOTID_SKIRT_RIGHT = 0x5A,
	CARSLOTID_SPOILER = 0x5B,
	CARSLOTID_STEERINGWHEEL = 0x5C,
	CARSLOTID_TRUNK = 0x5D,
	CARSLOTID_UNIVERSAL_SPOILER_BASE = 0x5E,
	CARSLOTID_WHEEL_FRONT = 0x5F,
	CARSLOTID_WHEEL_REAR = 0x60,
	CARSLOTID_WINDOW_FRONT = 0x61,
	CARSLOTID_WINDOW_FRONT_LEFT = 0x62,
	CARSLOTID_WINDOW_FRONT_RIGHT = 0x63,
	CARSLOTID_WINDOW_REAR = 0x64,
	CARSLOTID_WINDOW_REAR_LEFT = 0x65,
	CARSLOTID_WINDOW_REAR_RIGHT = 0x66,
	CARSLOTID_BRAKE_PACKAGE = 0x67,
	CARSLOTID_DRIVETRAIN_PACKAGE = 0x68,
	CARSLOTID_ENGINE_PACKAGE = 0x69,
	CARSLOTID_FORCED_INDUCTION_PACKAGE = 0x6A,
	CARSLOTID_INTERIOR = 0x6B,
	CARSLOTID_LIVERY = 0x6C,
	CARSLOTID_NITROUS_PACKAGE = 0x6D,
	CARSLOTID_SUSPENSION_PACKAGE = 0x6E,
	CARSLOTID_TIRE_FRONT = 0x6F,
	CARSLOTID_TIRE_PACKAGE = 0x70,
	CARSLOTID_TIRE_REAR = 0x71,
	CARSLOTID_VECTORVINYL = 0x72,
	CARSLOTID_NUM = 0x73,
	CARSLOTID_MODEL_FIRST = 0x0,
	CARSLOTID_MODEL_LAST = 0x66,
	CARSLOTID_MODEL_NUM = 0x67,
	CARSLOTID_FIRST_NONRENDER = 0x67,
	CARSLOTID_LAST_NONRENDER = 0x72,
	CARSLOTID_NONRENDER_NUM = 0xC,
	CARSLOTID_DAMAGE_MODEL_FIRST = 0x17,
	CARSLOTID_DAMAGE_MODEL_LAST = 0x37,
	CARSLOTID_DAMAGE_MODEL_NUM = 0x21,
	CARSLOTID_DECAL_MODEL_FIRST = 0x38,
	CARSLOTID_DECAL_MODEL_LAST = 0x39,
	CARSLOTID_DECAL_MODEL_NUM = 0x2,
};

enum KIT_TYPE {
	KIT_TYPE_BASE = 0,
	KIT_TYPE_STOCK = 1,
	KIT_TYPE_AUTOSCULPT = 2,
	KIT_TYPE_WIDEBODY = 3,
	NUM_KIT_TYPE = 4,
};

struct CarPaintRecordPacked {
	unsigned int group;
	uint8_t hue;
	float saturation;
	float variance;
};

struct PackedVinylColor {
	uint8_t swatch;
	uint8_t saturation;
	uint8_t brightness;
};

namespace VinylsAttrib {
	enum VinylFinish {
		VinylFinishMatte = 0,
		VinylFinishGloss = 1,
		VinylFinishChrome = 2,
	};
}

namespace VinylSystem {
	class VinylTransformPacked {
	public:
		int16_t translationX;
		int16_t translationY;
		uint8_t rotation;
		uint8_t scaleX;
		uint8_t scaleY;
		uint8_t shear : 7;
		uint8_t proportionalScale : 1;
	};
}

class PackedVinylLayer {
public:
	int16_t vinylPart;
	VinylSystem::VinylTransformPacked transform;
	PackedVinylColor colors[4];
};

class PackedDecalLayer {
public:
	int16_t decalPart;
	VinylSystem::VinylTransformPacked transform;
	PackedVinylColor color;
};

class VehicleCustomizations {
public:
	class InstalledPart {
	public:
		unsigned int part_key;
		unsigned int kit_num;
	};

	int16_t GUID[5];
	unsigned int creatorId;
	char creatorName[32];
	unsigned int shareNumber;
	VehicleCustomizations::InstalledPart InstalledParts[115];
	uint8_t customPaintsValid[12];
	CarPaintRecordPacked customPaints[12];
	uint8_t partBaseMaterials[12];
	BluePrintType bluePrintType;
	KIT_TYPE kitType;
	unsigned int kitNum;
	float RideHeight;
	PackedVinylLayer VinylLayers[20];
	int VinylMirrorBits;
	int NumVinylLayers;
	PackedDecalLayer DecalLayers[20];
	int DecalMirrorBits;
	int NumDecalLayers;
	int LiveryID;
	uint8_t MorphValues[40][11];
	float PhysicsTuning[32];
	int Type;
	VinylsAttrib::VinylFinish vinylFinish;
	unsigned int PresetRide;
	CAR_SLOT_ID RemovedParts[4];
};
static_assert(sizeof(VehicleCustomizations) == 0x9EC);